AQUA_LEADER  EQU $00 ; *
TEAM_AQUA_M  EQU $01 ; TEAM AQUA*
TEAM_AQUA_F  EQU $02 ; TEAM AQUA*
; no AQUA ADMIN
AROMA_LADY   EQU $03
RUIN_MANIAC  EQU $04
INTERVIEWER  EQU $05 ; *
TUBER_F      EQU $06 ; TUBER
TUBER_M      EQU $07 ; TUBER
COOLTRAINER_M EQU $08 ; COOLTRAINER♂
COOLTRAINER_F EQU $09 ; COOLTRAINER♀
HEX_MANIAC   EQU $0A
LADY         EQU $0B
BEAUTY       EQU $0C
RICH_BOY     EQU $0D
POKEMANIAC   EQU $0E ; POKéMANIAC
SWIMMER_M    EQU $0F ; SWIMMER♂
TC_BLACK_BELT EQU $10 ; item name
GUITARIST    EQU $11
KINDLER      EQU $12
CAMPER       EQU $13
BUG_MANIAC   EQU $14
PSYCHIC_M    EQU $15 ; PSYCHIC
PSYCHIC_F    EQU $16 ; PSYCHIC
GENTLEMAN    EQU $17
ELITE_FOUR_SIDNEY EQU $18 ; ELITE FOUR*
ELITE_FOUR_PHOEBE EQU $19 ; ELITE FOUR*
LEADER_ROXANNE   EQU $1A ; LEADER*
LEADER_BRAWLY    EQU $1B ; LEADER*
LEADER_TATE_LIZA EQU $1C ; LEADER*
SCHOOL_KID_M EQU $1D ; SCHOOL KID
SCHOOL_KID_F EQU $1E ; SCHOOL KID
SR_AND_JR    EQU $1F ; SR. AND JR.*
; no WINSTRATE
POKEFAN_M    EQU $20 ; POKéFAN
POKEFAN_F    EQU $21 ; POKéFAN
EXPERT_M     EQU $22 ; EXPERT
EXPERT_F     EQU $23 ; EXPERT
YOUNGSTER    EQU $24
CHAMPION     EQU $25 ; *
FISHERMAN    EQU $26
TRIATHLETE_M_BIKE EQU $27 ; TRIATHLETE
TRIATHLETE_F_BIKE EQU $28 ; TRIATHLETE
TRIATHLETE_M_RUN  EQU $29 ; TRIATHLETE
TRIATHLETE_F_RUN  EQU $2A ; TRIATHLETE
TRIATHLETE_M_SWIM EQU $2B ; TRIATHLETE
TRIATHLETE_F_SWIM EQU $2C ; TRIATHLETE
DRAGON_TAMER EQU $2D
BIRD_KEEPER  EQU $2E
NINJA_BOY    EQU $2F
BATTLE_GIRL  EQU $30
PARASOL_LADY EQU $31
SWIMMER_F    EQU $32 ; SWIMMER♀
PICNICKER    EQU $33
TWINS        EQU $34 ; *
SAILOR       EQU $35
BOARDER_1    EQU $36 ; *
BOARDER_2    EQU $37 ; *
COLLECTOR    EQU $38
PKMN_TRAINER_WALLY     EQU $39 ; \{PKMN} TRAINER*
PKMN_TRAINER_BRENDAN_1 EQU $3A ; \{PKMN} TRAINER*
PKMN_TRAINER_BRENDAN_2 EQU $3B ; \{PKMN} TRAINER*
PKMN_TRAINER_BRENDAN_3 EQU $3C ; \{PKMN} TRAINER*
PKMN_TRAINER_MAY_1     EQU $3D ; \{PKMN} TRAINER*
PKMN_TRAINER_MAY_2     EQU $3E ; \{PKMN} TRAINER*
PKMN_TRAINER_MAY_3     EQU $3F ; \{PKMN} TRAINER*
PKMN_BREEDER_M EQU $40 ; \{PKMN} BREEDER
PKMN_BREEDER_F EQU $41 ; \{PKMN} BREEDER
PKMN_RANGER_M  EQU $42 ; \{PKMN} RANGER
PKMN_RANGER_F  EQU $43 ; \{PKMN} RANGER
MAGMA_LEADER EQU $44 ; *
TEAM_MAGMA_M EQU $45 ; *
TEAM_MAGMA_F EQU $46 ; *
; no MAGMA ADMIN
LASS         EQU $47
BUG_CATCHER  EQU $48
HIKER        EQU $49
YOUNG_COUPLE EQU $4A ; *
OLD_COUPLE   EQU $4B ; *
SIS_AND_BRO  EQU $4C ; *
; $4D: BLACK BELT with a Lass sprite
; $4E: PKMN TRAINER with a Youngster sprite
; $4F: GUITARIST with a Youngster sprite
; $8F: GENTLEMAN with a PKMN Breeder sprite
; $FB: TWINS with May’s sprite
; $FC: PKMN TRAINER with a Pokéfan (♂) sprite
; $FD: SAILOR with May’s sprite
; $FE: PKMN TRAINER with a Sis and Bro sprite
; $FF: BOARDER with May’s sprite